#@TYPE: Machine
#@NAME: stm32mp1-som
#@DESCRIPTION: Emcraft STM32MP1 SOM
#@NEEDED_BSPLAYERS: layers/meta-openembedded/meta-oe layers/meta-openembedded/meta-python

include conf/machine/stm32mp1-disco.conf
BOOTSCHEME_LABELS = "trusted"
FLASHLAYOUT_CONFIG_LABELS = "emmc"
FLASHLAYOUT_CONFIG_LABELS += "sdcard"
UBOOT_CONFIG[trusted] = "stm32mp1_som_defconfig,,u-boot.stm32"
UBOOT_CONFIG[basic] = "stm32mp1_som_defconfig,,u-boot.stm32"
STM32MP_DT_FILES_EV = "stm32mp1-som"
